replaced "if, multipe else-if, else" sequence with switch
managarm/managarm pull request #300
Opened 2021-05-14 21:44 UTC by cflaviu

- replaced "if, multipe else-if, else" sequence with switch
- replaced multiple string comparisons with switch
- fixed warnings
- small improvements

2021-05-15 09:23 UTC, avdgrinten commented
Thank you for the PR and for splitting up the commits. This is now a lot easier to review. I can review this within the next two days.

We will probably merge #288 first; this might cause some conflicts, but we can probably just drop the corresponding commits from this PR.

2021-05-19 07:47 UTC, cflaviu commented
Welcome. I solved the conflicts.

2021-05-28 18:43 UTC, cflaviu commented on posix/subsystem/src/main.cpp
>  			if(killed)
missing !

2021-05-28 19:40 UTC, Dennisbonke requested changes
In general, a few places have the weird `default:;` thing that I'm not entirely sure about. Furthermore, I'm not sure if refactoring all `if`, `else-if` statements to `switch` statements is needed, in some places it gets a bit ugly. For all files I want to comment that the indentation is off, we indent the `case` statements one level relative to the `switch` statement. Also, we only do one statement per line, which is not followed in several places. Lastly, as a general note, I didn't see any major issues with the commit messages, but when in doubt follow [this](https://docs.managarm.org/handbook/contributing/commit-messages.html). As a reference, [this](https://docs.managarm.org/handbook/contributing/coding-style.html) is the coding style I'm referencing to.

2021-05-28 19:40 UTC, Dennisbonke commented on core/drm/src/core.cpp
> +			case 24: return DRM_FORMAT_XRGB8888;
Conform the [coding style](https://docs.managarm.org/handbook/contributing/coding-style.html), we should put the return statements on their own line.

2021-05-28 19:40 UTC, Dennisbonke commented on core/virtio/src/core.cpp
> +			case 1: common_mapping = std::move(mapping);
Same here, statements are on their own line.

2021-05-28 19:40 UTC, Dennisbonke commented on drivers/kbd/src/main.cpp
> +		{
This brace should not be on it's own line.

2021-05-28 19:40 UTC, Dennisbonke commented on drivers/libevbackend/src/libevbackend.cpp
> +	default:;
What is this `;` doing here?

2021-05-28 19:40 UTC, Dennisbonke commented on drivers/libterminal/src/libterminal.cpp
> +void Emulator::printString(const std::string& text){
`const std::string& text` should be `const std::string &text`.

2021-05-28 19:40 UTC, Dennisbonke commented on drivers/libblockfs/src/ext2fs.cpp
> +		inode->fileType = kTypeRegular; break;
Every statement should be on it's own line, so the `break;` would be it's own line.

2021-05-28 19:40 UTC, Dennisbonke commented on drivers/libterminal/src/libterminal.cpp
> +		case 0:	for(int i = cursorX; i < width; i++) {
Statements should be on their own line here too.

2021-05-28 19:40 UTC, Dennisbonke commented on drivers/usb/hcds/xhci/src/main.cpp
> +	auto& value = _commandRing->ent[_enqueuePtr].val[3];
`auto& value` should be `auto &value`.

2021-05-28 19:40 UTC, Dennisbonke commented on drivers/usb/hcds/xhci/src/main.cpp
> +	auto& value = _transferRing->ent[_enqueuePtr].val[3];
Same here.

2021-05-28 19:40 UTC, Dennisbonke commented on kernel/eir/arch/arm/arch.cpp
> +		new_entry |= kPageGRE | kPageOuterSh; break;
One statement per line.

2021-05-28 19:40 UTC, Dennisbonke commented on kernel/eir/arch/arm/raspi4/raspi4.cpp
> +		case 4:	initrd = p->asU32(); break;
Same here, only one statement per line.

2021-05-28 19:40 UTC, Dennisbonke commented on kernel/thor/arch/x86/thor-internal/arch/cpu.hpp
> +		{
This brace is wrong.

2021-05-28 19:40 UTC, Dennisbonke commented on kernel/thor/generic/hel.cpp
> +	}
Seems like an extra white space was added here.

2021-05-28 19:40 UTC, Dennisbonke commented on kernel/thor/generic/servers.cpp
> +			//	   we would have to map the file's memory. Hence, we do not implement
This entire comment block should just be refactored to be C style comments, as should all multiline comments. Imo the expected alignment would probably look like this
```
/*
 * TODO: Verify that the file ....
 * we would have to ....
 * it for now.
 */
 ```

2021-05-28 19:40 UTC, Dennisbonke commented on kernel/thor/system/pci/pci_discover.cpp
> +		auto&& value) {
Pointers and references are declared like `const char *name`, not `const char* name`.

2021-05-28 19:40 UTC, Dennisbonke commented on kernel/thor/system/pci/pci_discover.cpp
> +	void addProperty(managarm::mbus::CntRequest<KernelAlloc>& req, const char* name, auto... args) {
I think `auto... args` should be `auto ... args` or something like that?

2021-05-28 19:40 UTC, Dennisbonke commented on posix/subsystem/src/main.cpp
> +	for(bool killed = false; !killed && !generation->inTermination; ) {
what is the advantage of the `for` loop over the `while` loop? Imo the `while` loop makes it very clear that this loops indefinitely until broken out of and that can not be said for the `for` loop.

2021-05-28 19:40 UTC, Dennisbonke commented on utils/runsvr/src/main.cpp
> +{
The brace should not be on it's own line.

2021-05-28 19:40 UTC, Dennisbonke commented on utils/runsvr/src/main.cpp
> +{
Same here.

2021-05-28 19:40 UTC, Dennisbonke commented on utils/runsvr/src/main.cpp
> +int main(int argc, const char *argv[]) {
`argc` is probably unused, thus triggering a warning. We don't want warnings so this should be removed.

2021-05-28 19:42 UTC, qookei commented on utils/runsvr/src/main.cpp
> +int main(int argc, const char *argv[]) {
I also don't see why the `**argv` to `*argv[]` change was done

2021-05-28 19:43 UTC, cflaviu commented on core/drm/src/core.cpp
> +		switch(req.drm_capability()) {
Inner switches should be functions but that is another step.

2021-05-28 19:45 UTC, Dennisbonke commented on core/drm/src/core.cpp
> +		switch(req.drm_capability()) {
Why would that be the next step?

2021-05-28 19:47 UTC, qookei commented on core/drm/src/core.cpp
> +		switch(req.drm_capability()) {
I don't see the benefit of moving it to it's own function, especially since it only has one user.

2021-05-28 19:49 UTC, cflaviu commented on core/drm/src/core.cpp
> +		for(size_t i = 0; i != crtcs.size(); i++) {
Just semantics: < has sense when step is not 1 (eg. greater than 1 or variable). In almost all cases (I would say 99%) we are just checking if limit is reached using step 1.

2021-05-28 19:51 UTC, Dennisbonke commented on core/drm/src/core.cpp
> +		for(size_t i = 0; i != crtcs.size(); i++) {
I still don't see the need for the change but that may just be me.

2021-05-28 19:53 UTC, Dennisbonke commented
Also, I'd like to note that this PR should pass the compilation with all warnings at meson warning level 2 enabled without disabling any specific warning and without introducing new ones. At this time, the github ci still has 3 warnings disabled but to my knowledge, (almost) all of those have been fixed by work in #288 and #287, and I'd like to keep it that way.

2021-05-28 19:54 UTC, cflaviu commented on core/drm/src/core.cpp
> +		switch(req.drm_capability()) {
Guidelines says a function should not exceed one view page. Readability is a benefit.

2021-05-28 19:56 UTC, qookei commented on core/drm/src/core.cpp
> +		for(size_t i = 0; i != crtcs.size(); i++) {
Yeah I'd say that's just personal preference, and I don't see the point of changing it in existing files

2021-05-28 19:56 UTC, cflaviu commented on core/drm/src/core.cpp
> +			case 24: return DRM_FORMAT_XRGB8888;
Clang-format would fix it instantly.

2021-05-28 19:56 UTC, cflaviu commented on core/virtio/src/core.cpp
> +			case 1: common_mapping = std::move(mapping);
This is why clang-format would be useful.

2021-05-28 19:58 UTC, cflaviu commented on drivers/libevbackend/src/libevbackend.cpp
> +	default:;
Static code analyzers are complaining if no default clause is defined and it helps on code robustness. 
Specifying default:; you simply say other cases will not be taken into account.

2021-05-28 20:00 UTC, Dennisbonke commented on drivers/libevbackend/src/libevbackend.cpp
> +	default:;
The default clause I get and agree on, I'm just not familiar with adding a `;` directly behind it, because I always see a separate `break;` or an `assert` or actual code in the default statement, which is why I asked.

2021-05-28 20:01 UTC, qookei commented on drivers/libevbackend/src/libevbackend.cpp
> +	default:;
I'd say for default cases that should not be reached we should do something like `assert(!"Unexpected value");` (or maybe throw an exception).

2021-05-28 20:01 UTC, cflaviu commented on drivers/usb/hcds/xhci/src/main.cpp
> +	auto& value = _commandRing->ent[_enqueuePtr].val[3];
Yeah, i used my coding style instinctively :)

2021-05-28 20:01 UTC, Dennisbonke commented on drivers/libevbackend/src/libevbackend.cpp
> +	default:;
Agreed, and even the coding style strongly suggests it.

2021-05-28 20:01 UTC, cflaviu commented on drivers/usb/hcds/xhci/src/main.cpp
> +	auto& value = _transferRing->ent[_enqueuePtr].val[3];
Yeah, i used my coding style instinctively :)

2021-05-28 20:02 UTC, cflaviu commented on kernel/thor/arch/x86/thor-internal/arch/cpu.hpp
> +		{
instinctively :)

2021-05-28 20:04 UTC, cflaviu commented on kernel/thor/generic/servers.cpp
> +			//	   we would have to map the file's memory. Hence, we do not implement
Why using C style in C++ code?

2021-05-28 20:06 UTC, cflaviu commented on posix/subsystem/src/main.cpp
> +	for(bool killed = false; !killed && !generation->inTermination; ) {
You know breaks inside while-switch constructs will not break the loop. Using a boolean controlling the loop is a solution to that issue. If you have a better solution please let me know.

2021-05-28 20:06 UTC, cflaviu commented on utils/runsvr/src/main.cpp
> +{
k

2021-05-28 20:06 UTC, cflaviu commented on utils/runsvr/src/main.cpp
> +{
k

2021-05-28 20:09 UTC, cflaviu commented on utils/runsvr/src/main.cpp
> +int main(int argc, const char *argv[]) {
argc should be checked before accessing argv. **argv is useful iterating trough argument values using a pointer. I never seen that.

2021-05-28 20:11 UTC, cflaviu commented
> Also, I'd like to note that this PR should pass the compilation with all warnings at meson warning level 2 enabled without disabling any specific warning and without introducing new ones. At this time, the github ci still has 3 warnings disabled but to my knowledge, (almost) all of those have been fixed by work in #288 and #287, and I'd like to keep it that way.

If new warnings were introduced on this PR, they should be fixed. Old warnings should be fixed in other PR.

2021-05-28 20:17 UTC, qookei commented on utils/runsvr/src/main.cpp
> +int main(int argc, const char *argv[]) {
`**argv` and `*argv[]` are fully equivalent in this case, as seen by the following code compiling without errors:
```cpp
#include <type_traits>

void foo(char **a, char *b[]) {
    static_assert(std::is_same_v<decltype(a), decltype(b)>);
}
```

2021-05-28 21:43 UTC, cflaviu commented on utils/runsvr/src/main.cpp
> +int main(int argc, const char *argv[]) {
I didn't say those types are not equivalent. But are we using argv incrementing the pointer? Or always we use it with an index. This is the point.

2021-05-28 21:45 UTC, cflaviu commented on drivers/libevbackend/src/libevbackend.cpp
> +	default:;
This is a lesson learned after fixing QA C++ warnings : )

2021-05-28 21:45 UTC, cflaviu commented on drivers/kbd/src/main.cpp
> +		{
ok

2021-05-28 21:46 UTC, qookei commented on utils/runsvr/src/main.cpp
> +int main(int argc, const char *argv[]) {
Doesn't matter, you can index pointers as well.

2021-05-29 10:11 UTC, closed without merging