Add NVMe block driver
managarm/managarm pull request #304
Opened 2021-05-21 05:04 UTC by Jimx-

2021-05-21 14:32 UTC, avdgrinten commented
Thanks a lot for the PR! An NVMe driver is a very welcome addition to Managarm. You can expect the PR get a review soon. :smile: 

As a minor comment: the indentation is off in some places (tabs vs. spaces). It'd be nice to fix that.

2021-05-21 14:33 UTC, thomtl commented on drivers/block/nvme/src/command.cpp
> +        command_.readWrite.dataPtr.prp1 = convert_endian<endian::little, endian::native>(dmaAddr);
You're assigning to thesame thing twice here?

2021-05-21 14:33 UTC, thomtl commented on drivers/block/nvme/src/command.cpp
> +    command_.readWrite.dataPtr.prp1 = convert_endian<endian::little, endian::native>(prp2);
Once again assigning to thesame thing twice? Shouldn't the second one be dataPtr.prp2

2021-05-21 14:33 UTC, thomtl commented on drivers/block/nvme/src/controller.cpp
> +        if ((co_await identifyNamespaceList(prev, nsList.data())).first != 0)
The identify command for namespaces actually wasn't included on NVMe 1.0 controllers (Like the one VMWare emulates), only since 1.1.0 has it been supported, so this will break on 1.0 machines

2021-05-22 02:00 UTC, Jimx- commented
I have pushed some new commits to fix the issues. Do I need to replace all spaces with tabs for indentation in the code?

2021-05-22 03:16 UTC, 64 commented
It might also be nice to add the required qemu options in vm-utils.py to boot from NVMe (this will require a PR to bootstrap-managarm)

2021-05-22 03:42 UTC, Jimx- commented
> It might also be nice to add the required qemu options in vm-utils.py to boot from NVMe (this will require a PR to bootstrap-managarm)

I tried that but qemu's bios does not seem to support booting from nvme. If I have only one nvme drive in the qemu options (like                 qemu_args += ['-device', 'nvme,drive=boot-drive,serial=1234']) then qemu won't boot at all, complaining there is no bootable disk. When testing the driver, I need to set up both the nvme disk and another virtio-blk device for booting (it will crash later in device node creation because both the virtio driver and the nvme driver advertise the same sda0 disk but blockfs can read the FS information from nvme so the driver part should be ok). Don't know if I did something wrong here.

2021-05-22 09:12 UTC, qookei commented
> Do I need to replace all spaces with tabs for indentation in the code?

Yes, we use tabs for indentation. Also, pointers and references should be next to the name, not the type (`T *x` and `T &x`, not `T* x` and `T& x`).

2021-05-22 09:48 UTC, Dennisbonke commented
In general, try to follow [this](https://docs.managarm.org/handbook/contributing/coding-style.html) for the coding style. I didn’t see many issues apart from what others have already pointed out but I didn’t do a thorough review to be honest.

2021-05-22 09:59 UTC, qookei requested changes
Over all looks good, apart from the comments (most of which are mainly code-style related).

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/command.cpp
> +        HEL_CHECK(helPointerPhysical(view.data(), &physical));
We have convenience wrappers for this (`helix::ptrToPhysical` and `helix::addressToPhysical`), and it could be rewritten as:
```cpp
command_.common.dataPtr.prp1 = convert_endian<endian::little, endian::native>(
                helix::ptrToPhysical(view.data()));
```
Same applies to other places where `helPointerPhysical` is used.

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/controller.cpp
> +}
For small private namespaces we should indent their contents by 1 level.

Some of these could be defined using `arch::field`s instead. To do that, turn the associated register into a `arch::bit_register`, and add an `arch::field` for each field of a register you care about, for example:
```cpp
// first argument is the bit offset, second argument is the bit width
constexpr arch::field<uint64_t, uint16_t> mqes{0, 16};

constexpr arch::field<uint64_t, uint8_t> iocqes{20, 4};
constexpr arch::field<uint64_t, uint8_t> iosqes{16, 4};
constexpr arch::field<uint64_t, bool> enable{0, 1};
```
Then, to get the value of the field from the register, you'd do something like:
```cpp
auto cap = regs_.load(regs::cap);
auto val = cap & cap::mqes;
```
and to update the field values you'd do:
```cpp
auto cc = regs_.load(regs::cc);
// This preserves the other values in cc and only replaces the fields we specify
// Use | instead of / if you don't want to clear out the bits used by the fields we modify
auto val = cc / cc::iosqes(6) / cc::iocqes(4) / cc::enable(true);
regs_.store(regs::cc, val);
```

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/controller.cpp
> +    co_return;
Explicit `co_return` is not needed if the function returns a `async::result<void>` and is already a coroutine (already has a `co_await` somewhere).

Also, these functions don't need to be coroutines, you can just turn this function, `waitStatus`, and other functions that only read from/write to registers into regular functions (drop the `async::result<>` from the return type and drop all the `co_await`s), since they don't actually perform any async operations.

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/namespace.cpp
> +}
Put the member initializer list on it's own line, on the same level as `Namespace::Namespace`. Same applies to other places where this is on the same line.

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/queue.cpp
> +    sqCmds_ = reinterpret_cast<spec::CompletionEntry *>(window);
Here using a `arch::dma_array<spec::CompletionEntry>` (or at least a `arch::dma_buffer`) would be better than manually allocating the memory and having the `reinterpret_cast`.

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/queue.cpp
> +    volatile spec::CompletionEntry* cqe = &cqes_[cqHead_];
Why do we need `volatile` here?

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/queue.hpp
> +    async::queue<std::unique_ptr<Command>, stl_allocator> pendingCmdQueue_;
Include `<frg/std_compat.hpp>` and use `frg::stl_allocator` instead.

2021-05-22 09:59 UTC, qookei commented on drivers/block/nvme/src/controller.hpp
> +public:
Prefer `struct Foo {` over `class Foo { public:`

2021-05-22 12:36 UTC, Jimx- commented on drivers/block/nvme/src/queue.cpp
> +    sqCmds_ = reinterpret_cast<spec::CompletionEntry *>(window);
But dma_array does not guarantee the allocated buffer is page-aligned, right?

2021-05-22 12:37 UTC, Jimx- commented on drivers/block/nvme/src/queue.cpp
> +    volatile spec::CompletionEntry* cqe = &cqes_[cqHead_];
Not sure if the cpu can read stale values if volatile is dropped because the device can be posting CQEs at the same time.

2021-05-22 12:41 UTC, Jimx- commented on drivers/block/nvme/src/controller.hpp
> +public:
But Controller also has private members.

2021-05-22 12:44 UTC, qookei commented on drivers/block/nvme/src/controller.hpp
> +public:
`struct`s can also have private members just like classes.

2021-05-22 12:47 UTC, qookei commented on drivers/block/nvme/src/queue.cpp
> +    sqCmds_ = reinterpret_cast<spec::CompletionEntry *>(window);
Hm that is a fair point, does NVMe require that the queues are page aligned?

2021-05-22 13:36 UTC, Jimx- commented on drivers/block/nvme/src/queue.cpp
> +    sqCmds_ = reinterpret_cast<spec::CompletionEntry *>(window);
Yes, if I use dma_array then the create CQ command fails with base address misaligned error.

2021-05-22 14:08 UTC, qookei commented on drivers/block/nvme/src/queue.cpp
> +    sqCmds_ = reinterpret_cast<spec::CompletionEntry *>(window);
Alright, I think for now this will be fine then until we have some way to allocate memory with a specified alignment.

2021-05-23 11:07 UTC, qookei approved these changes
LGTM now

2021-05-23 12:45 UTC, 64 commented
someone needs to approve the CI run

2021-05-24 12:44 UTC, avdgrinten commented
Alright, I think we can merge this now. I will squash the commits into one. Again, thank you very much for the PR!

2021-05-24 12:44 UTC, merged