kernel: refactored createObject coroutine
managarm/managarm pull request #342
Opened 2021-06-07 16:00 UTC by cflaviu

2021-06-07 16:31 UTC, avdgrinten requested changes

2021-06-07 16:36 UTC, Dennisbonke commented
In several places the [coding style](https://docs.managarm.org/handbook/contributing/coding-style.html) is not followed. Please fix the inconsistencies.

2021-06-07 16:37 UTC, avdgrinten commented on kernel/thor/system/pci/pci_discover.cpp
> +	void addProperty(managarm::mbus::CntRequest<KernelAlloc>& req, const char* name, auto... args) {
Actually we also need the `int padding` as an argument since it's sometimes 4 and sometimes 2.

2021-06-07 16:58 UTC, cflaviu commented on kernel/thor/system/pci/pci_discover.cpp
> +		auto&& value) {
OK

2021-06-07 17:00 UTC, cflaviu commented
> In several places the [coding style](https://docs.managarm.org/handbook/contributing/coding-style.html) is not followed. Please fix the inconsistencies.

I will fix them. Thanks

2021-06-09 20:21 UTC, avdgrinten reviewed
Looks good now. Two small comments below. You can squash all your commits into one and then we can merge it.

2021-06-09 20:21 UTC, avdgrinten commented on kernel/thor/system/pci/pci_discover.cpp
> +		unsigned int value, int padding = 2) {
I think we should remove the default argument here to make the code more explicit at the call site.

2021-06-09 20:21 UTC, avdgrinten commented on kernel/thor/system/pci/pci_discover.cpp
> +		frg::string<KernelAlloc> &&text) {
It's probably better to take a value and not a rvalue reference here (the only thing that we potentially save is a move but moves are cheap anyway).

2021-06-09 21:38 UTC, cflaviu commented on kernel/thor/system/pci/pci_discover.cpp
> +		unsigned int value, int padding = 2) {
I thought the caller code would be simpler, ok.

2021-06-09 21:38 UTC, cflaviu commented on kernel/thor/system/pci/pci_discover.cpp
> +		frg::string<KernelAlloc> &&text) {
OK

2021-06-10 07:39 UTC, avdgrinten approved these changes
LGTM, thank you for the PR!

2021-06-10 07:39 UTC, merged