netserver/tcp: Add getsockname and getpeername
managarm/managarm pull request #417
Opened 2022-02-04 01:40 UTC by Dennisbonke

`OpenSSH` makes use of `sockname()` and `peername()` on tcp sockets. Implement this functionality so `OpenSSH` at least somewhat knows who it is talking to.

2022-02-04 08:46 UTC, ArsenArsen requested changes

2022-02-04 08:46 UTC, ArsenArsen commented on servers/netserver/src/ip/tcp4.cpp
> +		co_return 128;
Incorrect return value?

2022-02-04 08:46 UTC, ArsenArsen commented on servers/netserver/src/ip/tcp4.cpp
> +		co_return 128;
Incorrect return value?

These functions should return zero even if the address is trimmed. I could be forgetting how we utilize these return values, though,

2022-10-18 23:16 UTC, Dennisbonke commented
I believe I've addressed the comments made, ready for another round.

2022-10-19 00:20 UTC, no92 approved these changes

2022-11-06 11:14 UTC, ArsenArsen requested changes

2022-11-06 11:14 UTC, ArsenArsen commented on servers/netserver/src/ip/tcp4.cpp
> +		co_return destSize;
```
DESCRIPTION
       getsockname() returns the current address to which the socket sockfd is bound, in the buffer pointed to by
       addr.  The addrlen argument should be initialized to indicate the amount of space (in bytes) pointed to by
       addr.  On return it contains the actual size of the socket address.

       The returned address is truncated if the buffer provided is too small; in this case, addrlen will return a
       value greater than was supplied to the call.

RETURN VALUE
       On success, zero is returned.  On error, -1 is returned, and errno is set to indicate the error.
```

2022-11-06 11:14 UTC, ArsenArsen requested changes

2022-11-06 11:14 UTC, ArsenArsen commented on servers/netserver/src/ip/tcp4.cpp
> +		co_return destSize;
ditto

2023-11-26 23:13 UTC, Dennisbonke commented
Superseeded by #595

2023-11-26 23:13 UTC, closed without merging