Fix multiple issues regarding EHCI stack and HID
managarm/managarm pull request #438
Opened 2022-04-12 03:49 UTC by borrrden

- The assertions happening in the EHCI controller regarding clean state transition appear to not be reliable for more than one device being connected to the controller.  The port connections will be happening simultaneously and there is no guaranteed starting state for them to be in.
- Implemented TODO for handing off port to UHCI in the event that it is not a high speed device
- Added the FEATURE (0xB0) token to the list of recognized tokens for HID

2022-08-08 14:29 UTC, Dennisbonke approved these changes
It looks good to me but needs another review.

2022-08-08 14:31 UTC, Dennisbonke commented
@avdgrinten or @qookei can we review this PR?

2022-09-05 13:56 UTC, ArsenArsen commented
please split up this commit and reword it to align with the rest of the repository

2022-09-05 13:58 UTC, ArsenArsen requested changes

2022-09-05 13:58 UTC, ArsenArsen commented on drivers/usb/hcds/ehci/src/ehci.hpp
> +	void portDisabled(int port);
This function could be named better

2022-09-05 13:58 UTC, ArsenArsen commented on drivers/usb/devices/hid/src/main.cpp
> +				printf("usb-hid:      Feature: 0x%x\n", data);
there's an extra space here in the string

2023-07-24 20:25 UTC, no92 commented
Superseded by #545.

2023-07-24 20:25 UTC, closed without merging