thor/svm: Implement basic SVM support + virtualization test
managarm/managarm pull request #455
Opened 2022-05-24 13:00 UTC by thomtl

2022-05-24 20:53 UTC, qookei requested changes
Some places have wrong indentation (4 spaces instead of a tab). Also some other style nitpicks, like left-side pointers.

2022-05-24 20:53 UTC, qookei commented on kernel/thor/generic/address-space.cpp
> -		assert(actualAddress);
This should propagate the error back to user-space

2022-05-24 20:53 UTC, qookei commented on kernel/thor/arch/x86/cpu.cpp
> +		assert(svmSupported ^ vmxSupported);
Won't this fail on machines with neither SVM or VMX (are there any x86_64 machines like that)?

2022-05-24 21:15 UTC, thomtl commented on kernel/thor/arch/x86/cpu.cpp
> +		assert(svmSupported ^ vmxSupported);
The assertion was useless anyway, because SVM is AMD and VMX is Intel it never occurs that both are set

2022-05-26 13:38 UTC, avdgrinten commented on kernel/thor/arch/x86/npt.cpp
> +							}
This will free physical pages mapped into this NptSpace, right? That looks wrong.

2022-05-26 13:49 UTC, thomtl commented on kernel/thor/arch/x86/npt.cpp
> +							}
Yeah that most certainly seems wrong, I had just copied that code from VMX EPT, so I'll remove it from there as well

2022-06-04 22:42 UTC, Dennisbonke requested changes
Looks good, a few code style issues.

2022-06-04 22:42 UTC, Dennisbonke commented on kernel/thor/arch/x86/npt.cpp
> +Error thor::svm::NptSpace::store(uintptr_t guestAddress, size_t size, const void* buffer) {
Code style violation, it's `const void *buffer`.

2022-06-04 22:42 UTC, Dennisbonke commented on kernel/thor/arch/x86/npt.cpp
> +Error thor::svm::NptSpace::load(uintptr_t guestAddress, size_t size, void* buffer) {
Code style violation, it's `void *buffer`.

2022-06-04 22:42 UTC, Dennisbonke commented on kernel/thor/arch/x86/thor-internal/arch/npt.hpp
> +#pragma once
The entire file has mixed indentation, please fix.

2022-06-04 22:42 UTC, Dennisbonke commented on kernel/thor/arch/x86/thor-internal/arch/npt.hpp
> +	    Error store(uintptr_t guestAddress, size_t len, const void* buffer);
Code style violation, it's `const void *buffer`.

2022-06-04 22:42 UTC, Dennisbonke commented on kernel/thor/arch/x86/thor-internal/arch/npt.hpp
> +	    Error load(uintptr_t guestAddress, size_t len, void* buffer);
Code style violation, it's `void *buffer`.

2022-06-04 22:42 UTC, Dennisbonke commented on kernel/thor/arch/x86/thor-internal/arch/svm.hpp
> +		Vcpu& operator=(const Vcpu &) = delete;
Code style violation, it's `Vcpu &`.

2022-06-04 22:42 UTC, Dennisbonke commented on testsuites/virt-test/main.cpp
> +int main() {
Please use tabs for indentation.

2022-06-04 22:42 UTC, Dennisbonke commented on testsuites/virt-test/main.cpp
> +    void* fake_ptr;
Code style violation, it's `void *`.

2022-06-04 22:42 UTC, Dennisbonke commented on testsuites/virt-test/main.cpp
> +    void* actual_ptr;
Code style violation, it's `void *`.

2022-06-04 22:42 UTC, Dennisbonke commented on testsuites/virt-test/main.cpp
> +    HEL_CHECK(helLoadRegisters(vcpu, kHelRegsVirtualization, (void*)&regs));
Code style violation, it's `void *`.

2022-06-04 22:42 UTC, Dennisbonke commented on testsuites/virt-test/main.cpp
> +    memcpy((uint8_t*)actual_ptr + 0x7C00, code, sizeof(code));
Code style violation, it's `uint8_t *`.

2022-07-14 10:15 UTC, avdgrinten commented
Maybe @qookei can do a final review, then we can merge.

2022-08-08 11:37 UTC, qookei approved these changes

2022-08-08 14:22 UTC, no92 approved these changes
Other than the marked magic values, LGTM.

2022-08-08 14:22 UTC, no92 commented on kernel/thor/arch/x86/cpu.cpp
> +			if(!(leaf[2] & (1 << 2)))
Instead of relying on magic values, using constants would make this more readable.

2022-08-08 14:22 UTC, no92 commented on kernel/thor/arch/x86/cpu.cpp
> +			if(vm_cr & (1 << 4)) {
Magic value.

2022-08-08 14:22 UTC, no92 commented on kernel/thor/arch/x86/cpu.cpp
> +			if(!(leaf[3] & (1 << 0)))
Magic value.

2022-08-08 14:22 UTC, no92 commented on kernel/thor/arch/x86/svm.cpp
> +		vmcb->cr0 = (1 << 4) | (1 << 29) | (1 << 30);
Magic values.

2022-08-08 14:22 UTC, no92 commented on kernel/thor/arch/x86/svm.cpp
> +			case 0x78: // HLT
Changing these to constants would make this cleaner.

2022-08-08 15:15 UTC, Dennisbonke requested changes
With my limited knowledge it looks good to me, some styling comments remain.

2022-08-08 15:15 UTC, Dennisbonke commented on kernel/thor/arch/x86/npt.cpp
> +	//TODO
We should probably log a message here.

2022-08-08 15:15 UTC, Dennisbonke commented on kernel/thor/arch/x86/npt.cpp
> +	//TODO
We should probably log a message here.

2022-08-08 15:15 UTC, Dennisbonke commented on kernel/thor/arch/x86/svm.cpp
> +		vmcb->iceptExceptions = (1 << 1) | (1 << 6) | (1 << 14) | (1 << 17) | (1 << 18);
A bunch of magic numbers, maybe add a comment explaining what they mean?

2022-08-17 09:06 UTC, thomtl commented on kernel/thor/arch/x86/cpu.cpp
> +			if(!(leaf[2] & (1 << 2)))
CPUID magic values are used all over thor, I don't believe it is a good idea to change that in a commit dedicated to implementing SVM

2022-08-28 23:55 UTC, Dennisbonke commented
So can this be merged then?

2022-08-29 05:14 UTC, thomtl commented
> So can this be merged then?

Yes, as far as I'm aware

2022-09-03 14:36 UTC, merged