posix: implement FIONREAD for fifo.read
managarm/managarm pull request #471
Opened 2022-08-08 11:48 UTC by no92

2022-08-08 14:12 UTC, Dennisbonke requested changes
LGTM apart from 2 styling issues. Where did you observe this being a problem?

2022-08-08 14:12 UTC, Dennisbonke commented on posix/subsystem/src/fifo.cpp
> +#include <sys/ioctl.h>
Missing newline after this line.

2022-08-08 14:12 UTC, Dennisbonke commented on posix/subsystem/src/fifo.cpp
> +	async::result<void>
Missing newline.

2022-09-05 14:02 UTC, ArsenArsen commented on posix/subsystem/src/fifo.cpp
> +					resp.set_fionread_count(packet->buffer.size() - packet->offset);
is there ever more than one element in the queue? iterating the whole thing would probably also avoid the size check

2022-09-10 11:16 UTC, no92 commented
Addressed the comments raised above.

2022-09-10 15:38 UTC, ArsenArsen requested changes

2022-09-10 15:38 UTC, ArsenArsen commented on posix/subsystem/src/fifo.cpp
> +				if(_channel->packetQueue.empty()) {
this check is now redundant as a result of using std::acumulate

2022-09-10 15:38 UTC, ArsenArsen commented on posix/subsystem/src/fifo.cpp
> +					size_t count = std::accumulate(_channel->packetQueue.cbegin(), _channel->packetQueue.cend(), 0, [](size_t sum, const Packet &p) {
this could also be `reduce` (since this operation does not rely on iteration order), but in practice, here it doesn't make a difference

2022-09-17 16:54 UTC, ArsenArsen approved these changes

2022-09-17 16:55 UTC, merged