eir: scan for RSDP when booting with multiboot1
managarm/managarm pull request #473
Opened 2022-08-09 22:28 UTC by cleanbaja

closes #125, and fully shifts ACPI scanning out of the kernel

2022-08-09 22:35 UTC, 64 requested changes

2022-08-09 22:35 UTC, 64 commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +    	return checksum;
There is some mixed indentation here (managarm uses tabs)

2022-08-09 22:35 UTC, 64 commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +    bda_data = *bda_window;
```suggestion
    uint16_t bda_data = *reinterpret_cast<uint16_t*>(0x40E);
```

2022-08-09 22:35 UTC, 64 commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +    	return checksum;
Also, variables should be camel case (sorry :smile:)

2022-08-09 23:15 UTC, no92 requested changes

2022-08-09 23:15 UTC, no92 commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> -    auto do_checksum = [](void* ptr, size_t len) {
Applying a clang-format should be left for a future PR that defines that file. The best way would be to drop this commit, and amend/fixup the style corrections in the first commit.

2022-08-10 01:43 UTC, circutrider21 commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> -    auto do_checksum = [](void* ptr, size_t len) {
Okay then

2022-08-10 12:22 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
>  namespace eir {
Missing newline

2022-08-10 12:22 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +	auto do_checksum = [](void* ptr, size_t len) {
Managarm uses right pointers

2022-08-10 12:23 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +			checksum += reinterpret_cast<uint8_t*>(ptr)[i];
Missing space between uint8_t and *

2022-08-10 12:25 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +		for (size_t i = 0; i < len; i++)
No spaces between `for` and the opening `(`

2022-08-10 12:26 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +		uint8_t* region = reinterpret_cast<uint8_t*>(base);
Right side pointers and missing space between uint8_t and *

2022-08-10 12:26 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +		for (size_t off = 0; off < len; off += 16) {
No space between for and (

2022-08-10 12:26 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +			acpi_rsdp_t *rsdp = reinterpret_cast<acpi_rsdp_t*>(region + off);
Missing space between acpi_rsdp_t and *

2022-08-10 12:27 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +			if (memcmp(rsdp->signature, "RSD PTR ", 8))
No space between if and (

2022-08-10 12:27 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +			if (do_checksum(static_cast<void*>(rsdp), sizeof(acpi_rsdp_t)) != 0)
Missing space between void and *

2022-08-10 12:27 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +			if (!rsdp->revision) {
No space between if and (

2022-08-10 12:28 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +				if (do_checksum(static_cast<void*>(xsdp), sizeof(acpi_xsdp_t)))
Missing space between void and *

2022-08-10 12:28 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +	uint16_t bda_data = *reinterpret_cast<uint16_t*>(0x40E);
Missing space between uint16_t and *

2022-08-10 12:28 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +	if (scan_zone(ebda_base, 0x400))
No space between if and (

2022-08-10 12:28 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +	if (scan_zone(0xE0000, 0x20000))
No space between if and (

2022-08-10 12:28 UTC, Dennisbonke commented on kernel/eir/arch/x86/multiboot1/multiboot1.cpp
> +	if (!findAcpiRsdp(info_ptr))
No space between if and (

2022-08-11 08:35 UTC, avdgrinten approved these changes
LGTM.

2022-08-11 08:36 UTC, no92 approved these changes
LGTM

2022-08-11 08:36 UTC, merged