netserver: implement RTM_GETROUTE rtnetlink request
managarm/managarm pull request #499
Opened 2022-11-07 15:12 UTC by Geertiebear

2022-12-08 00:14 UTC, Dennisbonke commented
Bump on this, can we get this merged in?

2022-12-08 21:07 UTC, no92 approved these changes
Other than the minor issues pointed out, LGTM.

2023-01-02 23:13 UTC, no92 requested changes

2023-01-02 23:13 UTC, no92 commented on posix/subsystem/src/sockutil.hpp
> -#pragma once
There are still multiple places including this file.

2023-03-31 08:31 UTC, no92 commented
Closing as #510 is merged now.

2023-03-31 08:31 UTC, closed without merging