Posix wait
managarm/managarm pull request #513
Opened 2023-02-05 17:31 UTC by ikbenlike

This PR aims to implement the `pid = 0` and `pid <= -1` cases in `Process::wait`. It also adds checks in `init-stage2` to ensure that processes launched with `execl` actually get executed.

2023-02-06 10:35 UTC, ArsenArsen requested changes

2023-02-06 10:35 UTC, ArsenArsen commented on posix/init/src/stage2.cpp
> +		assert(-1 != execl("/usr/sbin/udevd", "udevd", "--debug", nullptr));
Building with NDEBUG should not remove udev.

This definitely classifies as assert abuse.

Instead, we can write a wrapper macro that calls `error()`

2023-02-06 10:35 UTC, ArsenArsen commented on posix/subsystem/src/process.cpp
> +			else if(pid < -1 && groupid != it->gid()){
Why are these cases distinct?

2023-02-06 10:35 UTC, ArsenArsen commented on posix/subsystem/src/requests.cpp
> +
We really need a better way to map managarm errors to posix (not something for you to address, just saying)

2023-02-06 11:05 UTC, ikbenlike commented on posix/subsystem/src/process.cpp
> +			else if(pid < -1 && groupid != it->gid()){
I did it like this because I was just going down the list of cases in the man-page; they do mean different things but because they all just `continue;` it could also be one singular if-statement if so desired

2023-02-06 11:09 UTC, ikbenlike commented on posix/init/src/stage2.cpp
> +		assert(-1 != execl("/usr/sbin/udevd", "udevd", "--debug", nullptr));
Good point. I'll write a wrapper that calls `error()` and then terminates by either calling `exit()` or `abort()` (whichever is deemed more appropriate).

2023-02-06 11:11 UTC, ikbenlike commented on posix/subsystem/src/requests.cpp
> +
Agreed, doing it this way feels clunky and the amount of code overhead isn't really optimal. I was thinking about just returning a POSIX error from `Process::wait`, but that didn't seem appropriate either

2023-02-06 20:29 UTC, ArsenArsen commented on posix/init/src/stage2.cpp
> +		assert(-1 != execl("/usr/sbin/udevd", "udevd", "--debug", nullptr));
error(3) terminates after printing the error if passed a nonzero value as the exit code

2023-02-10 14:08 UTC, ikbenlike commented on posix/init/src/stage2.cpp
> +		assert(-1 != execl("/usr/sbin/udevd", "udevd", "--debug", nullptr));
This has been implemented; however due to the absense of `error()` in mlibc this is stuck on [mlibc#793](https://github.com/managarm/mlibc/pull/793)

2023-04-30 15:26 UTC, qookei requested changes
Indentation is wrong in some places (4 spaces instead of a tab). Also `else` goes on the same line as the closing `}` of the `if` body (as in: `} else {`)

2025-03-19 18:46 UTC, no92 commented
Superseded by #760.

2025-03-19 18:46 UTC, closed without merging