posix: Remove several netlink asserts
managarm/managarm pull request #525
Opened 2023-04-09 09:35 UTC by Dennisbonke

WebKitGTK ran into these asserts, but commenting them out broke nothing. Seems to me that some if not all of these asserts are thus either wrong or not needed.

I'm not sure if this is correct, so someone with knowledge about this should review this.

2023-04-09 16:40 UTC, ikbenlike commented
it might be better to turn some of these into error returns to propagate the error up the call chain - but then it would probably be good to test what impact this would have on WebKitGTK

2023-04-09 17:21 UTC, ArsenArsen requested changes
as he said..  each we can't just randomly remove these

2023-04-09 17:42 UTC, Dennisbonke commented
I'm aware that we can't just remove them (unless they are wrong obviously). I was hoping to get some information on what to do with them (turn into some error return? Change the assert? Log unsupported flags for the flags assert?).

2023-04-09 18:03 UTC, no92 requested changes
We can mostly drop these asserts, but some minor modifications might be needed to make it correct.

2023-04-09 18:03 UTC, no92 commented on posix/subsystem/src/nl-socket.cpp
> -		assert(!flags);
We should probably warn about flags we don't support, e.g. by printing the flags `if(!(flags & ~(MSG_DONTWAIT | MSG_CMSG_CLOEXEC)))`, as is done in similar fashion elsewhere, too. Unsupported flags should be silently ignored AFAICT (looking at the man page and POSIX).

2023-05-16 19:58 UTC, no92 approved these changes
LGTM

2023-05-16 20:17 UTC, merged