posix: Pass ucontext to signal handlers
managarm/managarm pull request #552
Opened 2023-08-13 19:27 UTC by Qwinci

Change signal code to pass ucontext to signal handlers and add a kHelRegsSignal registerset that matches the linux layout to helLoadRegisters/helStoreRegisters/helQueryRegisterInfo.

2023-08-13 19:37 UTC, avdgrinten commented on kernel/thor/generic/hel.cpp
> +		thread->_executor.general()->cs = regs[18] | 3;
`rflags` probably needs to be filtered (e.g., to disallow IOPL changes). We should probably have a mask of allowed bits and keep all other bits invariant.

Restricting `cs` like this sounds fine. Maybe we should add a comment here to explain why it's done though.

2023-08-13 19:45 UTC, Qwinci commented on kernel/thor/generic/hel.cpp
> +		thread->_executor.general()->cs = regs[18] | 3;
Yeah those are good points. Ill do that and then see if aarch64 needs a similar thing.

2023-10-08 13:53 UTC, qookei requested changes
The aarch64 portion is borked

2023-10-08 13:53 UTC, qookei commented on kernel/thor/generic/hel.cpp
> +		constexpr uintptr_t allowedFlagsMask = 0b1111 << 28 | 1 << 21;
`0b1111 << 28` leads to sign extension, so the mask ends up being `0xFFFFFFFFF0200000`. Making the `0b1111` (e.g. `0b1111U`) unsigned fixes that.

2023-10-08 13:53 UTC, qookei commented on posix/subsystem/src/process.cpp
> +	ucontext_t ucontext;
This change should also apply to the aarch64 definition below?

2023-10-16 16:23 UTC, qookei reviewed
With the exception of that one comment it looks good now.

2023-10-17 22:48 UTC, Qwinci commented on posix/subsystem/src/process.cpp
> +	sf.ucontext.uc_mcontext.fpregs = (struct _fpstate*)(frame + sizeof(SignalFrame));
Yeah, I added a todo for aarch64 because I am not sure how it should be implemented.

2023-10-17 22:53 UTC, qookei approved these changes

2023-10-21 22:57 UTC, qookei commented
Does not compile on AArch64:
```
../../../src/managarm/posix/subsystem/src/process.cpp:749:26: error: no member named 'x' in 'sigcontext'
        sf.ucontext.uc_mcontext.x[0] = item->signalNumber;
        ~~~~~~~~~~~~~~~~~~~~~~~ ^
../../../src/managarm/posix/subsystem/src/process.cpp:750:26: error: no member named 'x' in 'sigcontext'
        sf.ucontext.uc_mcontext.x[1] = frame + offsetof(SignalFrame, info);
        ~~~~~~~~~~~~~~~~~~~~~~~ ^
../../../src/managarm/posix/subsystem/src/process.cpp:751:26: error: no member named 'x' in 'sigcontext'
        sf.ucontext.uc_mcontext.x[2] = frame + offsetof(SignalFrame, ucontext);
        ~~~~~~~~~~~~~~~~~~~~~~~ ^
../../../src/managarm/posix/subsystem/src/process.cpp:754:26: error: no member named 'x' in 'sigcontext'
        sf.ucontext.uc_mcontext.x[30] = handler.restorerIp;
        ~~~~~~~~~~~~~~~~~~~~~~~ ^
```
AFAICS the array is called `regs`

2023-10-21 23:02 UTC, qookei commented
Also, I just noticed that the AArch64 code doesn't actually set PC or SP, or store the modified registers back to set parameters up.

2023-10-21 23:06 UTC, qookei commented on posix/subsystem/src/process.cpp
> +	sf.ucontext.uc_mcontext.x[30] = handler.restorerIp;
```suggestion
	sf.ucontext.uc_mcontext.x[30] = handler.restorerIp;
	
	sf.ucontext.uc_mcontext.pc = handler.handlerIp;
	sf.ucontext.uc_mcontext.sp = frame;

	HEL_CHECK(helStoreRegisters(thread.getHandle(), kHelRegsSignal, &sf.ucontext.uc_mcontext));
```

2023-10-21 23:07 UTC, qookei commented on posix/subsystem/src/process.cpp
> +	sf.ucontext.uc_mcontext.x[30] = handler.restorerIp;
```suggestion
	sf.ucontext.uc_mcontext.regs[30] = handler.restorerIp;

	sf.ucontext.uc_mcontext.pc = handler.handlerIp;
	sf.ucontext.uc_mcontext.sp = frame;

	HEL_CHECK(helStoreRegisters(thread.getHandle(), kHelRegsSignal, &sf.ucontext.uc_mcontext));
```

2023-10-21 23:07 UTC, qookei commented on posix/subsystem/src/process.cpp
> +	sf.ucontext.uc_mcontext.x[2] = frame + offsetof(SignalFrame, ucontext);
```suggestion
	sf.ucontext.uc_mcontext.regs[0] = item->signalNumber;
	sf.ucontext.uc_mcontext.regs[1] = frame + offsetof(SignalFrame, info);
	sf.ucontext.uc_mcontext.regs[2] = frame + offsetof(SignalFrame, ucontext);
```

2023-10-22 08:48 UTC, Qwinci commented
Should be fixed now, not sure where I got the `x` from.

2023-10-23 00:21 UTC, qookei approved these changes

2023-10-23 00:21 UTC, merged