thor: Add helGetCurrentCpu syscall
managarm/managarm pull request #581
Opened 2023-10-20 11:42 UTC by Qwinci

2023-10-20 11:45 UTC, no92 approved these changes
LGTM

2023-10-20 19:46 UTC, qookei commented on hel/include/hel.h
> +HEL_C_LINKAGE HelError helGetCurrentCpu(int *index);
Could you document this?

2023-10-20 19:53 UTC, ElectrodeYT requested changes
One thing

2023-10-20 19:53 UTC, ElectrodeYT commented on kernel/thor/generic/main.cpp
> +		*image.error() = helGetCurrentCpu((int*)arg0);
This should not use output paramters; this should use `*image.out{}`

2023-10-20 21:04 UTC, Qwinci commented on kernel/thor/generic/main.cpp
> +		*image.error() = helGetCurrentCpu((int*)arg0);
I changed it to use out0. And I assume helSyscall0_1 is the correct one to use in hel-syscalls.h for that?

2023-10-20 21:07 UTC, ElectrodeYT commented on kernel/thor/generic/main.cpp
> +		*image.error() = helGetCurrentCpu((int*)arg0);
Yep, it should be. However, you should still be returning a HelError in `*image.error()`. Returning `kHelErrNone` unconditionally should suffice.

2023-10-23 00:07 UTC, Dennisbonke approved these changes
LGTM

2023-10-23 00:23 UTC, merged