General sysfs block improvements
managarm/managarm pull request #591
Opened 2023-10-23 22:14 UTC by Dennisbonke

This PR exposes some more attributes over sysfs for blockdevices. Most are hardcoded to a sane value (R/O is always zero), some are just a placeholder (size being 3.3G) and some are correct (major:minor number). This makes `lsblk` show `sda0`!

2023-10-23 22:43 UTC, qookei commented on posix/subsystem/src/subsystem/block.cpp
> +	int major;
No need to add new members, this is stored by `UnixDevice`, and can be accessed with `UnixDevice::getId()` (this returns the `DeviceId`, which is a `std::pair<int, int>` so the major is `.first`, minor is `.second`).

2023-10-23 22:43 UTC, qookei commented on posix/subsystem/src/subsystem/block.cpp
> +		char minorBuf[4];
Theoretically (at least on Linux) the major can be anywhere in the range [0, 4096), and the minor anywhere in the range [0, 1048576), so in this file at least the minor buffer should maybe be larger? (considering the major is always assigned to 8 for these devices).

Perhaps we could just use `std::to_string` instead of `snprintf` since we're not doing any fancy formatting?

2023-10-23 22:43 UTC, qookei commented on posix/subsystem/src/subsystem/block.cpp
> +	sprintf(buffer, "6942069\n");
Again `std::to_string`, although this is hardcoded anyway.

2023-11-12 19:51 UTC, ElectrodeYT requested changes

2023-11-12 19:51 UTC, ElectrodeYT commented on drivers/libblockfs/src/libblockfs.cpp
> +			assert(req);
This should be:
```cpp
			if (!req) {
				std::cout << "libblockfs: Rejecting request due to decoding failure" << std::endl;
				break;
			}
```

2023-11-12 19:51 UTC, ElectrodeYT commented on posix/subsystem/src/subsystem/block.cpp
> +	sprintf(buffer, "%d:%d\n", dev.first, dev.second);
This doesn't seem safe, are we sure that using a static sized buffer (especially one of this size) is a good idea here?

2023-11-12 20:27 UTC, ElectrodeYT approved these changes
LGTM

2023-11-12 20:49 UTC, Dennisbonke reviewed
Found one issue.

2023-11-12 20:49 UTC, Dennisbonke commented on drivers/libblockfs/src/libblockfs.cpp
> +				std::cout << "\e[31m" "core/drm: Unknown ioctl() message with ID "
This isn't core/drm, this is libblockfs.

2023-11-12 20:51 UTC, no92 commented on drivers/libblockfs/src/libblockfs.cpp
> +				std::cout << "\e[31m" "core/drm: Unknown ioctl() message with ID "
Fixed.

2023-11-13 00:55 UTC, qookei approved these changes

2023-11-13 00:57 UTC, merged