posix: Implement `/proc/[pid]/fd`.
managarm/managarm pull request #641
Opened 2024-03-18 19:59 UTC by Dennisbonke

Massive thanks to @48cf for the help!
Also brings some drive by fixes in error handling.

2024-03-18 21:52 UTC, qookei commented on posix/subsystem/src/epoll.cpp
> +	: File{StructName::get("epoll"), nullptr, SpecialLink::makeSpecialLink(VfsType::regular, 0777), File::defaultPipeLikeSeek}, _currentSeq{0} { }
Note: On Linux these files (epoll, inotify, eventfd, signalfd, etc) have file type 0, not regular. I don't think this really matters, as I assume nothing expects the type to be 0 anyway (coreutils' `stat` says "weird file", and that's only if the type isn't any of the ones it expects).

2024-03-19 02:18 UTC, qookei requested changes

2024-03-19 02:18 UTC, qookei commented on posix/subsystem/src/procfs.cpp
> +	if(_iter != _process->fileContext()->fileTable().end()) {
This introduces a race between the reader and target processes, which can result in a posix-subsystem crash.

The target process can change it's open files in some way that causes iterators to be invalidated between the construction of `FdDirectoryFile` and a  `readEntries` call, or between two `readEntries` calls.

Unsure of what a good solution to work around this would be. Taking a copy of the file table seems too expensive (maybe it's not too bad if it's just a map of int to pointer?), and locking the file table is not really possible either (you could block processes from opening any file descriptors by not letting go of your open `fd` directory).

2024-03-19 02:18 UTC, qookei commented on posix/subsystem/src/procfs.cpp
> +	co_return nullptr; // TODO: Return an error code.
Why not return `Error::noSuchFile` here?

2024-03-28 12:57 UTC, Dennisbonke commented on posix/subsystem/src/procfs.cpp
> +	if(_iter != _process->fileContext()->fileTable().end()) {
Fixed

2024-03-28 19:57 UTC, qookei approved these changes

2024-03-29 14:02 UTC, no92 approved these changes
LGTM

2024-03-29 14:02 UTC, merged