Fix LLVM 18 warnings and remove protobuf
managarm/managarm pull request #652
Opened 2024-04-07 12:39 UTC by no92

This PR fixes new warnings emitted by LLVM 18. As a bonus, all remaining protobuf protocols have been converted to bragi, as protobuf was producing massive amounts of warnings.

2024-04-07 12:55 UTC, Dennisbonke requested changes
Quick glance showed me one error

2024-04-07 12:55 UTC, Dennisbonke commented on tools/bakesvr/src/main.cpp
> +	app.add_option("-o,--output", output, "Path to the input file")->required();
This should say path to the output file.

2024-04-07 13:29 UTC, qookei commented on hel/include/hel.h
> +	uint32_t flags = 0;
I don't think these default member initializers are correct. This header is supposed to be usable from both C and C++, and C doesn't support them.

2024-04-07 13:29 UTC, qookei commented on drivers/usb/hcds/xhci/src/xhci.hpp
> -		Controller *_controller;
I think we can just remove this member completely instead.

2024-04-07 13:29 UTC, qookei commented on tools/bakesvr/meson.build
> +executable('bakesvr', src, dependencies: [yaml_cpp_dep, cli11_dep, bragi_dep], install_dir : get_option('bindir'), native: true, install: true)
Could you reformat this? Spaces around `:` on both sides, and one option per line.

2024-04-08 20:15 UTC, no92 commented
Addressed the comments raised.

2024-04-08 20:33 UTC, qookei approved these changes

2024-04-08 20:39 UTC, merged