Additions for dhcpcd
managarm/managarm pull request #662
Opened 2024-05-09 13:26 UTC by no92

2024-05-09 21:47 UTC, no92 commented
Marking as ready for review, as this PR provides the managarm changes needed to make `dhcpcd` work. In order to merge `dhcpcd`, some mlibc changes will be required; these are being cleaned up now, but might take a few days to complete.

2024-05-09 22:11 UTC, ArsenArsen commented on servers/netserver/src/bpf/bpf.cpp
> +#define bpf_log_op(args...) if(logBpfOps) { printf("\t[%.2zu/%.2zu] ", pc, prog_.size() - 1); printf(args); puts(""); } while(0)
why is this a macro?

2024-05-10 14:23 UTC, no92 commented on servers/netserver/src/bpf/bpf.cpp
> +#define bpf_log_op(args...) if(logBpfOps) { printf("\t[%.2zu/%.2zu] ", pc, prog_.size() - 1); printf(args); puts(""); } while(0)
Originally, for quick implementation convenience; the fixup replaces it with a lambda.

2024-05-11 13:10 UTC, ElectrodeYT requested changes
Mostly LGTM, but we should really stop adding more asserts like these, if possible...

2024-05-11 13:10 UTC, ElectrodeYT commented on servers/netserver/src/bpf/bpf.cpp
> +	assert(!"invalid BPF filter with no return!");
We should probably not be asserting on something like this

2024-05-11 13:10 UTC, ElectrodeYT commented on servers/netserver/src/bpf/bpf.cpp
> +				assert(!"unhandled BPF instruction");
We should probably not be asserting on something like this

2024-05-11 13:11 UTC, no92 commented on servers/netserver/src/bpf/bpf.cpp
> +	assert(!"invalid BPF filter with no return!");
Any such BPF filter should be caught in the validation step, and as such this assert seems justified.

2024-05-11 13:12 UTC, no92 commented on servers/netserver/src/bpf/bpf.cpp
> +				assert(!"unhandled BPF instruction");
Given that the BPF support in this PR is only covering a part of the instruction set, failing catastrophically instead of silently failing seemed more appropriate.

2024-05-11 13:13 UTC, ElectrodeYT commented on servers/netserver/src/bpf/bpf.cpp
> +	assert(!"invalid BPF filter with no return!");
Probably, yeah, but might be better to log/return an error instead anyway

2024-05-11 16:33 UTC, ElectrodeYT commented on servers/netserver/src/bpf/bpf.cpp
> +				assert(!"unhandled BPF instruction");
We should not fail "silently", but returning an error or something is probably more appropriate imo

2024-05-15 20:33 UTC, no92 commented
This PR now includes the ioctls implemented in #589, superseding it once merged.

2024-05-19 19:42 UTC, no92 commented on servers/netserver/src/ip/udp4.cpp
> +	pollWait(void *obj, uint64_t past_seq, int mask, async::cancellation_token cancellation) {
I think this is correct, as we don't indent a function name (as opposed to e.g. parameters).

2024-05-19 19:47 UTC, no92 commented on servers/netserver/src/raw.cpp
> +		printf("netserver: unhandled setsockopt layer %d number %d\n", layer, number);
Updated the PR to return `ENOPROTOOPT`, as linux does.

2024-05-19 19:48 UTC, no92 commented on core/lib/bpf/bpf.cpp
> +				assert(!"unhandled BPF instruction");
Added a TODO, as currently it is very likely to be an unimplemented opcode, not an invalid BPF filter. In the future, doing error handling (like returning EINVAL) would be nice, making BPF failures very clear is quite important to me.

2024-05-24 19:53 UTC, ElectrodeYT approved these changes
LGTM

2024-05-27 21:10 UTC, qookei commented on servers/netserver/src/ip/udp4.cpp
> +	pollWait(void *obj, uint64_t past_seq, int mask, async::cancellation_token cancellation) {
It is how we format similarly long function decls in other places

2024-05-27 22:10 UTC, qookei approved these changes

2024-05-27 23:17 UTC, Dennisbonke approved these changes
LGTM

2024-05-27 23:18 UTC, merged