Unify netlink implementations, add baseline Generic Netlink support
managarm/managarm pull request #681
Opened 2024-06-10 19:24 UTC by no92

2024-06-10 21:19 UTC, no92 commented
This allows `genl ctrl ls` (part of the iproute2 package) et al. to run correctly.

2024-06-12 19:03 UTC, ElectrodeYT requested changes
A couple tiny things, but mostly LGTM

2024-06-12 19:03 UTC, ElectrodeYT commented on posix/subsystem/src/netlink/nl-socket.cpp
> +	else {
Probably not a style issue, but still IMO looks weird here for some reason

2024-06-12 19:05 UTC, no92 commented on posix/subsystem/src/netlink/nl-socket.cpp
>  	}
We usually don't do this, which is why we log the warning.

2024-06-12 19:08 UTC, ElectrodeYT approved these changes
LGTM

2024-06-12 19:22 UTC, merged

2024-06-13 12:40 UTC, Geertiebear reviewed
I still have some comments even though the PR was already merged

2024-06-13 12:40 UTC, Geertiebear commented on core/include/core/netlink.hpp
> +struct NetlinkFile {
What's the point of ``NetlinkFile``? afaict the inheritance is not used anywhere? but I might be missing something

2024-06-13 12:40 UTC, Geertiebear commented on core/include/core/netlink.hpp
> +inline std::optional<NetlinkAttrs<struct genlmsghdr>> NetlinkAttr(struct nlmsghdr *hdr, struct nl::packets::genl) {
The name ``NetlinkAttr`` for this function is extremely confusing, at a glance I would think this is a struct and not a function.

2024-06-13 12:40 UTC, Geertiebear commented on posix/subsystem/src/netlink/nlctrl.cpp
> +	auto nlh = reinterpret_cast<struct nlmsghdr *>(packet.buffer.data());
These can be replaced by placement news.

2024-06-13 12:40 UTC, Geertiebear commented on posix/subsystem/src/netlink/nlctrl.cpp
> +							if(filter_id.value() != id)
Replace these with an `and` clause.

2024-06-13 12:40 UTC, Geertiebear commented on posix/subsystem/src/netlink/nlctrl.cpp
> +				case CTRL_CMD_GETFAMILY: {
Making this entire clause a static function is not such a bad idea, there is a hefty amount of indentation going in here, so much so that it's making it hard to review.

2024-06-13 17:16 UTC, no92 commented on posix/subsystem/src/netlink/nl-socket.cpp
>  	configure(NETLINK_ROUTE, 32, nullptr);
The configure function here registers the protocols, but the dispatch between the different protocols is handled elsewhere. Hence the registration of NETLINK_ROUTE with nullptr ops here.

2024-06-13 17:19 UTC, no92 commented on posix/subsystem/src/netlink/nlctrl.cpp
> +	auto nlh = reinterpret_cast<struct nlmsghdr *>(packet.buffer.data());
This is setting up a pointer to the nlmsghdr of the request, which is why we don't want to use placement new here (that would construct the object).

2024-06-13 17:21 UTC, no92 commented on core/include/core/netlink.hpp
> +struct NetlinkFile {
This interface is used by the utility functions (such as `sendDone`) and implemented by the OpenFile structs of the netlink implementations.

2024-06-13 17:24 UTC, no92 commented on posix/subsystem/src/netlink/nl-socket.cpp
> +	if(truncated_size < size) {
That would amount to the same, but we have this variable anyways (as it's used elsewhere) and makes the intent clearer IMO.

2024-06-13 17:25 UTC, no92 commented
For the remaining comments, I'll prepare a commit to address them.

2024-06-16 10:07 UTC, no92 commented
The comments are being addressed in #684.

2024-06-16 11:22 UTC, Geertiebear commented on posix/subsystem/src/netlink/nl-socket.cpp
> +	if(truncated_size < size) {
The variable is useless tho since you can pass ``max_length`` when ``MSG_TRUNC`` is set.

2024-06-16 11:24 UTC, no92 commented on posix/subsystem/src/netlink/nl-socket.cpp
> +	if(truncated_size < size) {
The if body is about setting MSG_TRUNC for the reply, and MSG_TRUNC on the request doesn't play into this? I guess I don't quite understand your point yet.

2024-06-16 11:24 UTC, Geertiebear commented on posix/subsystem/src/netlink/nl-socket.cpp
>  	configure(NETLINK_ROUTE, 32, nullptr);
Where does the dispatch take place?

2024-06-16 11:26 UTC, no92 commented on posix/subsystem/src/netlink/nl-socket.cpp
>  	configure(NETLINK_ROUTE, 32, nullptr);
https://github.com/managarm/managarm/blob/c6e8bb0f68790927ed6634f7e12f22979427a081/posix/subsystem/src/requests.cpp#L2455-L2472

2024-06-16 11:30 UTC, Geertiebear commented on posix/subsystem/src/netlink/nl-socket.cpp
>  	configure(NETLINK_ROUTE, 32, nullptr);
Right, so ``nl_socket`` never receives any call on the protocol NETLINK_ROUTE, so I don't understand why it needs to be configured.

2024-06-16 11:32 UTC, no92 commented on posix/subsystem/src/netlink/nl-socket.cpp
>  	configure(NETLINK_ROUTE, 32, nullptr);
Fair point.

2024-06-20 09:49 UTC, Geertiebear commented on core/include/core/netlink.hpp
> +struct NetlinkFile {
Yeah but I don't see any polymorphism in the rest of the code. Unless I've missed something, but it seems right now the virtual function is not necessary (and we can probably replace the run-time inheritance with compile-time inheritance)