amd pcne
managarm/managarm pull request #739
Opened 2024-11-09 00:24 UTC by Nivaturimika

draft

2024-11-11 01:18 UTC, no92 requested changes
Had a look over the code, haven't checked against the (surprisingly long) spec yet. While I can't boot managarm on VirtualBox, this currently does not work in VMWare due to the issues pointed out below. QEMU works fine for me, though.

A few general notes:
- Single-line if bodies can omit the curly braces
- after opening/before closing a namespace, we generally try to place a new line
- the comments' tone should be suitable for upstreaming :^)

I'll check this against the spec when I'm not as tired as now.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +namespace {
Same as above.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	//
Why is this a comment and not just an empty line?

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	virtual async::result<size_t> receive(arch::dma_buffer_view) override;
`virtual` and `override` one one line is unnecessary (possibly incorrect?), especially when the class isn't `final` IIRC.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +		assert(bar_index < 6 && "drivers/amdpcnet: unable to locate MMIO BAR!");
This will fail with older PCnet models that do not provide a MMIO bar. Instead, it would be fairly easy to handle the port I/O case, especially given the way how the device does register access.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	while(true) {
This would be better replaced by a for loop; we can only ever get 6 BARs, and the hw protocols only provides as many.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +		if(info.barInfo[bar_index].ioType == protocols::hw::IoType::kIoTypeMemory) {
I don't quite recall whether we should be checking this or `hostType`? CC @qookei

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	// Reset the fucker (in both modes, 16-bit and 32-bit)
Tone.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	// no (important) side effects! wohoo thanks pcnet i love you pcnet
Tone.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	co_await helix::sleepFor(1'000'000); // sleep for 1 microsecond
The sleeping part might be obvious :^)

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	auto* init = (InitializerDescriptor*)initializer_.data();
We right-align the `*`.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	init->ladr[0] = 0;
Seems like a perfect place for a `memset`, or even better, `std::fill`. There is no padding to worry here, the struct is packed.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	init->mac[0] = mac_[0];
`memecpy` would do the job here, too.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +		std::cout << "drivers/amdpcnet: 2434234" << std::endl;
Is this a debugging leftover?

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +	//promiscuous_ = true;
Why are these commented out?

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +			std::cout << "drivers/amdpcnet: got the fucking irq shit #" << sequence << "!!!" << std::endl;
Tone.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +		if(logDriverStuff) {
Might be nice to put this in a separate function so this can be reused.

2024-11-11 01:18 UTC, no92 commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +		assert(bar_index < 6 && "drivers/amdpcnet: unable to locate MMIO BAR!");
The port I/O case would need to be `#ifdef`ed away to only x86 though.

2024-11-11 01:18 UTC, no92 commented on servers/netserver/meson.build
> +	dep += nic_amdpcnet_dep
Is this necessarily limited to x86_64? This should work just fine on any other (little-endian) arch, right?

2024-11-12 03:32 UTC, Nivaturimika commented on servers/netserver/meson.build
> +	dep += nic_amdpcnet_dep
sure moved it above

2024-11-12 03:33 UTC, Nivaturimika commented on drivers/nic/amdpcnet/src/amdpcnet.cpp
> +		if(logDriverStuff) {
added print_status()

2024-11-12 17:04 UTC, no92 requested changes
Generally, this looks quite decent, bar some small comments. I don't quite have the time to do a full pass on the spec right now, so take this as the first chunk of that.

2024-11-12 19:16 UTC, Nivaturimika commented on drivers/nic/amdpcnet/src/pcnet.cpp
> +struct [[gnu::packed]] InitializerDescriptor {
it is set implicitly on reset

2024-11-15 01:16 UTC, qookei commented on drivers/nic/amdpcnet/src/pcnet.cpp
> +		__sync_synchronize();
Why is this done?

2025-09-01 06:46 UTC, closed without merging